### ISSUE TITLE
Export as text, as HTML and PDF

### ISSUE THREAD

**Issue by croqaz** [croqaz/clean-mark#1]
Good ideas for improvement.

- [x] export to markdown
- [x] export to text
- [x] export to html
- [ ] export to pdf

**Comment by rexpan** [comment]
@croqaz Could you publish export to HTML to npm.

**Comment by croqaz** [comment]
Sure thing !
It's done, version 0.4.4.
I didn't publish because the text conversion is crappy... I found some packages that convert HTML to text more cleanly, but I didn't have time to evaluate them.

I will fix the text conversion and add PDF and publish in v0.5.

**Comment by croqaz** [comment]
The purpose of this tool is to convert text to Markdown. Text and Html are bonuses. PDF will not happen.
