### ISSUE TITLE
clean-mark---command not found

### ISSUE THREAD

**Issue by behappy00** [croqaz/clean-mark#11]
just Simply install with npm: npm  install clean-mark --global ,,but i can't use it in the way you show

**Comment by croqaz** [comment]
Hi.
I tested it now and it seems to work, at least on Linux.
I did exactly these commands:

```sh
sudo npm install clean-mark --global
clean-mark --help
which clean-mark
# /usr/bin/clean-mark
ls -la /usr/lib/node_modules/clean-mark/
clean-mark https://medium.com/mind-cafe/12-things-i-stole-from-people-more-successful-than-me-d0ef5ef6cd84
```

Everything looks normal.
Can you run all these commands and see if any of them are not working?

**Comment by behappy00** [comment]
thanks
