### ISSUE TITLE
Feature request: allow sending result to stdout

### ISSUE THREAD

**Issue by Seirdy** [croqaz/clean-mark#4]
Sending the markdown to stdout instead of writing to a file would make it easier to use this program in larger scripts. I plan on piping the output through pandoc to apply some filters; I'm currently doing this with temp files, but it would be much cleaner to simply use pipes.

**Comment by croqaz** [comment]
Hi @Seirdy , thanks for your sugestion! Sounds like a good idea and a valid use-case.
This could be solved with a `--stdout` flag that will over-write the `--output` flag, so you can export the Markdown, HTML or Text in the terminal.
Should be a simple change, not sure if I have time to do it today, but soon.

**Comment by Seirdy** [comment]
A more standard approach would be `-o -`, to mimic the behavior of commands like `curl`.

**Comment by croqaz** [comment]
Hi, I implemented the `--stdout` option. I didn't follow the behaviour of `curl` because it's less intuitive to me. Also I think it's not a blocker for any user.
Thanks for taking the time to raise this issue. Feel free to close it's resolved.
