### ISSUE TITLE
Feature request: allow taking HTML from stdin

### ISSUE THREAD

**Issue by Seirdy** [croqaz/clean-mark#6]
A number of tools ranging from `curl` to [go-readability](https://github.com/go-shiori/go-readability) output raw HTML which can then be processed by clean-mark. Currently, clean-mark has no documented way to view anything besides a URL, so it can't work offline.

**Comment by croqaz** [comment]
Hi! I think I implemented this in the last commit https://github.com/croqaz/clean-mark/commit/63a46c4443751493ad8a2bc822e64d179054c0c4 . I didn't make a release, you probably need to clone the repo and test it.
If you think it's OK, you can close the issue and I'll release a new version.

**Comment by Seirdy** [comment]
Thanks!

It seems that combining STDIN with the `--stdout` flag causes a file to be written *and* sends the result to STDOUT, while passing a URL with the `--stdout` flag properly sends the result to STDOUT without writing the file.

Example:

``` sh
clean-mark --stdout <path/to/file.html
```

**Comment by croqaz** [comment]
You're absolutely right, the STDIN + --stdout option were broken, I forgot to return after printing the output.
Fixed in https://github.com/croqaz/clean-mark/commit/33aa228d055b97884a9b6d0c48972b9faeaa663b

**Comment by Seirdy** [comment]
Looks good now.
